# Generated by Django 2.1.3 on 2019-07-06 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='agree_conditions',
            field=models.BooleanField(default=True),
        ),
    ]
