# Generated by Django 2.2.3 on 2019-07-22 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_agree_conditions'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_nhs',
            field=models.BooleanField(default=False),
        ),
    ]
