# Generated by Django 2.1.3 on 2019-07-11 15:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seventhquestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seventh_one', models.FileField(upload_to='documents/')),
                ('seventh_two', models.FileField(upload_to='documents/')),
                ('seventh_three', models.FileField(upload_to='documents/')),
                ('seventh_four', models.FileField(upload_to='documents/')),
                ('seventh_five', models.TextField()),
                ('seventh_six', models.TextField()),
                ('seventh_seven', models.TextField()),
                ('seventh_eight', models.TextField()),
                ('developer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='projects.Project')),
            ],
        ),
    ]
