# Generated by Django 2.2.3 on 2019-07-23 09:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenthquestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenth_one', models.FileField(upload_to='documents/')),
                ('tenth_two', models.FileField(upload_to='documents/')),
                ('tenth_three', models.FileField(upload_to='documents/')),
                ('tenth_four', models.TextField()),
                ('tenth_five', models.FileField(upload_to='documents/')),
                ('tenth_six', models.TextField()),
                ('tenth_seven', models.FileField(upload_to='documents/')),
                ('tenth_eigth', models.TextField()),
                ('tenth_nine', models.TextField()),
                ('tenth_ten', models.TextField()),
                ('tenth_eleven', models.TextField()),
                ('developer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='projects.Project')),
            ],
        ),
    ]
