# Generated by Django 2.2.3 on 2019-07-23 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenthquestions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tenthquestion',
            old_name='tenth_eigth',
            new_name='tenth_eight',
        ),
    ]
