# Generated by Django 2.2.3 on 2019-08-23 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenthquestions', '0002_auto_20190723_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenthquestion',
            name='tenth_seven',
            field=models.TextField(),
        ),
    ]
