# Generated by Django 2.1.3 on 2019-07-08 12:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Secondquestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('second_one', models.TextField()),
                ('second_two', models.TextField()),
                ('second_three', models.TextField()),
                ('second_four', models.TextField()),
                ('second_five', models.TextField()),
                ('second_six', models.TextField()),
                ('second_seven', models.TextField()),
                ('second_eighth', models.TextField()),
                ('second_nine', models.TextField()),
                ('developer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='projects.Project')),
            ],
        ),
    ]
