# Generated by Django 2.1.3 on 2019-07-08 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secondquestions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='secondquestion',
            old_name='second_eighth',
            new_name='second_eight',
        ),
    ]
