# Generated by Django 2.1.3 on 2019-07-15 16:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ninthquestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ninth_one', models.TextField()),
                ('ninth_two', models.FileField(upload_to='documents/')),
                ('ninth_three', models.FileField(upload_to='documents/')),
                ('ninth_four', models.FileField(upload_to='documents/')),
                ('ninth_five', models.TextField()),
                ('ninth_six', models.TextField()),
                ('ninth_seven', models.FileField(upload_to='documents/')),
                ('developer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='projects.Project')),
            ],
        ),
    ]
