# Generated by Django 2.2.3 on 2019-08-23 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ninthquestions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ninthquestion',
            name='ninth_four',
            field=models.TextField(),
        ),
    ]
