# Generated by Django 2.2.3 on 2019-08-28 10:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ninthquestions', '0002_auto_20190823_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='ninthquestion',
            name='ninth_nine',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
