# Generated by Django 2.1.3 on 2019-07-15 14:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eighthquestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eighth_one', models.TextField()),
                ('eighth_two', models.TextField()),
                ('eighth_three', models.TextField()),
                ('eighth_four', models.TextField()),
                ('eighth_five', models.FileField(upload_to='documents/')),
                ('eighth_six', models.FileField(upload_to='documents/')),
                ('eighth_seven', models.FileField(upload_to='documents/')),
                ('eighth_eight', models.FileField(upload_to='documents/')),
                ('eighth_nine', models.FileField(upload_to='documents/')),
                ('eighth_ten', models.TextField()),
                ('eighth_eleven', models.TextField()),
                ('eighth_twelve', models.TextField()),
                ('developer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='projects.Project')),
            ],
        ),
    ]
