# Generated by Django 2.1.3 on 2019-07-09 16:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sixthquestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sixth_one', models.FileField(upload_to='documents/')),
                ('sixth_two', models.FileField(upload_to='documents/')),
                ('sixth_three', models.FileField(upload_to='documents/')),
                ('sixth_four', models.FileField(upload_to='documents/')),
                ('sixth_five', models.FileField(upload_to='documents/')),
                ('sixth_six', models.FileField(upload_to='documents/')),
                ('sixth_seven', models.FileField(upload_to='documents/')),
                ('sixth_eight', models.TextField()),
                ('sixth_nine', models.TextField()),
                ('sixth_ten', models.TextField()),
                ('sixth_eleven', models.TextField()),
                ('sixth_twelve', models.TextField()),
                ('developer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='projects.Project')),
            ],
        ),
    ]
