# Generated by Django 2.1.3 on 2019-07-07 23:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstquestions', '0002_auto_20190707_2342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firstquestion',
            name='project',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='projects.Project'),
        ),
    ]
