# Generated by Django 2.2.3 on 2019-08-23 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstquestions', '0003_auto_20190707_2350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='firstquestion',
            name='first_seven',
        ),
    ]
