# Generated by Django 2.1.3 on 2019-07-08 17:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Thirdquestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('third_one', models.TextField()),
                ('third_two', models.TextField()),
                ('third_three', models.TextField()),
                ('third_four', models.TextField()),
                ('third_five', models.TextField()),
                ('third_six', models.TextField()),
                ('third_seven', models.FileField(upload_to='')),
                ('third_eight', models.TextField()),
                ('third_nine', models.TextField()),
                ('third_ten', models.FileField(upload_to='')),
                ('developer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='projects.Project')),
            ],
        ),
    ]
