# Generated by Django 2.1.3 on 2019-07-08 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thirdquestions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thirdquestion',
            name='third_seven',
            field=models.FileField(upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='thirdquestion',
            name='third_ten',
            field=models.FileField(upload_to='documents/'),
        ),
    ]
