# Generated by Django 2.1.3 on 2019-07-08 19:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fourthquestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fourth_one', models.TextField()),
                ('fourth_two', models.TextField()),
                ('fourth_three', models.TextField()),
                ('fourth_four', models.TextField()),
                ('fourth_five', models.FileField(upload_to='documents/')),
                ('fourth_six', models.FileField(upload_to='documents/')),
                ('fourth_seven', models.TextField()),
                ('fourth_eight', models.FileField(upload_to='documents/')),
                ('fourth_nine', models.TextField()),
                ('fourth_ten', models.FileField(upload_to='documents/')),
                ('developer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='projects.Project')),
            ],
        ),
    ]
