# Generated by Django 2.2.3 on 2019-07-24 18:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fourthquestions', '0002_auto_20190724_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='fourthquestion',
            name='fourth_nine',
            field=models.FileField(default=django.utils.timezone.now, upload_to='documents/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fourthquestion',
            name='fourth_eight',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='fourthquestion',
            name='fourth_five',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='fourthquestion',
            name='fourth_seven',
            field=models.FileField(upload_to='documents/'),
        ),
    ]
